

#Copy all codes below, paste them into local/phpmyadmin in the SQL tabs.
CREATE DATABASE wavpool;
USE wavpool;
CREATE TABLE IF NOT EXISTS users(
	id INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(70) NOT NULL,
	salt VARCHAR(50) NOT NULL,
	premium INT(5) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sound(
	id INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	soundname VARCHAR(20) NOT NULL UNIQUE,
	url VARCHAR(120) NOT NULL 
);

CREATE TABLE IF NOT EXISTS soundOwner(
	id INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	uid INT(4) UNSIGNED NOT NULL,
	sid INT(4) UNSIGNED NOT NULL,
	FOREIGN KEY (uid) REFERENCES users(id),
	FOREIGN KEY (sid) REFERENCES sound(id)
);

CREATE TABLE IF NOT EXISTS mixes(
	id INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	categories VARCHAR(40) NOT NULL,
	public INT(4) NOT NULL,
	mix VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS mixesOwner(
	id INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uid INT(4) UNSIGNED NOT NULL,
	mid INT(4) UNSIGNED NOT NULL,
	FOREIGN KEY (uid) REFERENCES users(id),
	FOREIGN KEY (mid) REFERENCES mixes(id)
)


